// <auto-generated />
using System;
using Dodos.UI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Dodos.UI.Migrations {
    [DbContext (typeof (ApplicationContext))]
    [Migration ("20180129100736_init")]
    partial class init {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation ("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
#pragma warning restore 612, 618
        }
    }
}